### ISSUE TITLE
 Error building to develop a WebLLM package: Cannot find module 'tvmjs'

### ISSUE THREAD

**Issue by DekayKim** [mlc-ai/web-llm#200]
I followed that [URL](https://github.com/mlc-ai/web-llm#build-webllm-package-from-source) and ran build. but this error occured
 - install emcc & run script
    ```
   # ./scripts/prep_deps.sh
    + emcc --version
    emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.46 (19607820c447a13fd8d0b7680c56148427d6e1b8)
    Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
    This is free and open source software under the MIT license.
    There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    + npm --version
    9.8.1

    (...)

    found 0 vulnerabilities
    + cd ../..
    ```
 - Error after running a build
    ```
    # npm run build
    
    > @mlc-ai/web-llm@0.2.8 build
    > rollup -c && ./cleanup-index-js.sh

    src/index.ts → lib/index.js...
    [!] (plugin rpt2) Error: src/chat_module.ts:1:24 - error TS2307: Cannot find module 'tvmjs' or its corresponding type declarations.
    
    1 import * as tvmjs from "tvmjs";
                             ~~~~~~~
    
    src/index.ts
    
        at error (/Users/dekaykim/comRepo/web-llm/node_modules/rollup/dist/shared/rollup.js:198:30)
        at throwPluginError (/Users/dekaykim/comRepo/web-llm/node_modules/rollup/dist/shared/rollup.js:21718:12)
        at Object.error (/Users/dekaykim/comRepo/web-llm/node_modules/rollup/dist/shared/rollup.js:22672:20)
        at RollupContext.error (/Users/dekaykim/comRepo/web-llm/node_modules/rollup-plugin-typescript2/src/context.ts:35:17)
        at /Users/dekaykim/comRepo/web-llm/node_modules/rollup-plugin-typescript2/src/diagnostics.ts:70:17
        at Array.forEach (<anonymous>)
        at printDiagnostics (/Users/dekaykim/comRepo/web-llm/node_modules/rollup-plugin-typescript2/src/diagnostics.ts:42:14)
        at typecheckFile (/Users/dekaykim/comRepo/web-llm/node_modules/rollup-plugin-typescript2/src/index.ts:67:3)
        at Object.<anonymous> (/Users/dekaykim/comRepo/web-llm/node_modules/rollup-plugin-typescript2/src/index.ts:257:5)
        at Generator.next (<anonymous>)
    ```

So I changed the tvmjs setting in `package.json` to point the import to the web distribution version of `tvm_home`, and then ran the script: `npm install`
- before: `"tvmjs": "file:./tvm_home/web",`
- after: `"tvmjs": "file:./tvm_home/web/dist",`

However, several tvmjs methods are not executing.
- `ArtifactCache`, `createPolyfillWASI`, `registerInitProgressCallback`, etc.
<img width="733" alt="image" src="https://github.com/mlc-ai/web-llm/assets/23452118/954416d8-1414-4528-b6f2-2d08b1eb8536">

**Comment by djaffer** [comment]
facing this too

**Comment by DekayKim** [comment]
I found this problem. It was my mistake.

In order to set up `tvm_home`, the [relax](https://github.com/mlc-ai/relax) Repository, not [Apache tvm](https://github.com/apache/tvm), had to be cloned locally. (I got a hint from that [link](https://github.com/mlc-ai/web-llm/pull/121#issuecomment-1565568537))

I think it would be a good idea to reinforce that [part of the readme](https://github.com/mlc-ai/web-llm#build-webllm-package-from-source).

But I have a question. what is the difference between tvm and relax? It looks like it's a fork of tvm, but I'm not sure what the difference is.

**Comment by djaffer** [comment]
true, which is exactly what prep deps is doing.
