### ISSUE TITLE
[BUG] Find an error initializing the WebGPU device OperationError: D3D12

### ISSUE THREAD

**Issue by 0dminnimda** [mlc-ai/web-llm#22]
While running on the candy chrome i got those errors: (firstly the `Init error` and on the second request the rest)

```
[System Initalize] Initialize GPU device: WebGPU - intel
[System Initalize] Fetching param cache[71/163]: 1765MB fetched. 43% completed, 656 secs elapsed. It can take a while when we first visit this page to populate the cache. Later refreshes will become faster.
Init error, OperationError: The operation failed for an operation-specific reason
Find an error initializing the WebGPU device OperationError: D3D12 create command queue failed with DXGI_ERROR_DEVICE_REMOVED (0x887A0005) at CheckHRESULTImpl (..\..\third_party\dawn\src\dawn\native\d3d\D3DError.cpp:94) at Initialize (..\..\third_party\dawn\src\dawn\native\d3d12\DeviceD3D12.cpp:84) at Create (..\..\third_party\dawn\src\dawn\native\d3d12\DeviceD3D12.cpp:69)
Init error, Error: Find an error initializing WebGPU: OperationError: D3D12 create command queue failed with DXGI_ERROR_DEVICE_REMOVED (0x887A0005) at CheckHRESULTImpl (..\..\third_party\dawn\src\dawn\native\d3d\D3DError.cpp:94) at Initialize (..\..\third_party\dawn\src\dawn\native\d3d12\DeviceD3D12.cpp:84) at Create (..\..\third_party\dawn\src\dawn\native\d3d12\DeviceD3D12.cpp:69)
```

![image](https://user-images.githubusercontent.com/52697657/232326754-ecc14ff3-5f5a-40fe-986a-50646afcbe1e.png)
![image](https://user-images.githubusercontent.com/52697657/232326773-e7ec5d8a-bb93-4de6-9b74-3427712ff370.png)

console:
```
ID3D12Device::CreateCommittedResource failed with DXGI_ERROR_DEVICE_REMOVED (0x887A0005)
    at CheckHRESULTImpl (..\..\third_party\dawn\src\dawn\native\d3d\D3DError.cpp:94)
    at CreateCommittedResource (..\..\third_party\dawn\src\dawn\native\d3d12\ResourceAllocatorManagerD3D12.cpp:565)
    at AllocateMemory (..\..\third_party\dawn\src\dawn\native\d3d12\ResourceAllocatorManagerD3D12.cpp:391)
    at Initialize (..\..\third_party\dawn\src\dawn\native\d3d12\BufferD3D12.cpp:158)
    at Create (..\..\third_party\dawn\src\dawn\native\d3d12\BufferD3D12.cpp:105)
    at CreateBuffer (..\..\third_party\dawn\src\dawn\native\Device.cpp:1508)

llm_chat.js:547 undefined
llm_chat.js:421 undefined
llm_chat.js:547 Error: Find an error initializing WebGPU: OperationError: D3D12 create command queue failed with DXGI_ERROR_DEVICE_REMOVED (0x887A0005)
    at CheckHRESULTImpl (..\..\third_party\dawn\src\dawn\native\d3d\D3DError.cpp:94)
    at Initialize (..\..\third_party\dawn\src\dawn\native\d3d12\DeviceD3D12.cpp:84)
    at Create (..\..\third_party\dawn\src\dawn\native\d3d12\DeviceD3D12.cpp:69)

    at #asyncInitTVM (https://mlc.ai/web-llm/dist/llm_chat.js:423:13)
    at async LLMChatInstance.asyncInit (https://mlc.ai/web-llm/dist/llm_chat.js:443:5)
    at async LLMChatInstance.generate (https://mlc.ai/web-llm/dist/llm_chat.js:544:7)
    at async tvmjsGlobalEnv.asyncOnGenerate (https://mlc.ai/web-llm/dist/llm_chat.js:606:3)
```

**Comment by 0dminnimda** [comment]
It always seems to be stopped at 71/72

**Comment by tqchen** [comment]
what is your GPU RAM limit, since we are definitely pressure testing GPU a bit and if you do not have more than 6.5G of RAM, it might cause problems

**Comment by 0dminnimda** [comment]
![image](https://user-images.githubusercontent.com/52697657/232328666-7be92b79-c155-4645-97af-08be68f110ce.png)
![image](https://user-images.githubusercontent.com/52697657/232328686-3d7f5717-8785-43bb-83a6-f2c7dbcf745d.png)

**Comment by 0dminnimda** [comment]
It seems likely that the intel graphics card will fail after about 1765MB when the cap in 2160MB, including the fact that it renders the monitors

**Comment by 0dminnimda** [comment]
Although the candy chrome is using the nvidia
`chrome://gpu`:
```
<Discrete GPU> D3D12 backend - NVIDIA GeForce GT 750M
[WebGPU Status]
Available
```

**Comment by aseok** [comment]
facing this error while running on windows 10 x64 chrome Version 112.0.5615.121:
Error: Find an error initializing WebGPU: OperationError: Required limit (1073741824) is greater than the supported limit (268435456).
 - While validating maxBufferSize
 - While validating required limits

    at #asyncInitTVM (llm_chat.js:423:13)
    at async LLMChatInstance.asyncInit (llm_chat.js:443:5)
    at async LLMChatInstance.generate (llm_chat.js:544:7)
    at async tvmjsGlobalEnv.asyncOnGenerate (llm_chat.js:606:3)

**Comment by tqchen** [comment]
@aseok this is related to #21 , you can try to upgrade your browser to chrome 113(beta)

**Comment by tqchen** [comment]
@0dminnimda Unfortunately year the card's memory is not enough for this model, since we need ~ 6G , we will work on bringing more optimizations and smaller models
