### ISSUE TITLE
CLI run on MacOS error  "unrecognized arguments: --allreduce_strategy=RING"

### ISSUE THREAD

**Issue by flores-o** [mlc-ai/web-llm#345]
Hello, I am trying to run the example for [CLI](https://llm.mlc.ai/docs/deploy/cli.html) and getting the following error

```
(venv) oflorescu@Oanas-MacBook-Pro web-llm % python -m mlc_llm chat HF://mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC --overrides context_window_size=1024

[2024-03-25 22:54:32] INFO config.py:106: Overriding context_window_size from None to 1024
[2024-03-25 22:54:33] INFO auto_device.py:85: Not found device: cuda:0
[2024-03-25 22:54:34] INFO auto_device.py:85: Not found device: rocm:0
[2024-03-25 22:54:34] INFO auto_device.py:76: Found device: metal:0
[2024-03-25 22:54:35] INFO auto_device.py:85: Not found device: vulkan:0
[2024-03-25 22:54:36] INFO auto_device.py:85: Not found device: opencl:0
[2024-03-25 22:54:36] INFO auto_device.py:33: Using device: metal:0
[2024-03-25 22:54:36] INFO chat_module.py:362: Downloading model from HuggingFace: HF://mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC
[2024-03-25 22:54:36] INFO download.py:131: Weights already downloaded: /Users/oflorescu/.cache/mlc_llm/model_weights/mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC
[2024-03-25 22:54:36] INFO chat_module.py:781: Model lib not found. Now compiling model lib on device...
[2024-03-25 22:54:36] INFO jit.py:34: MLC_JIT_POLICY = ON. Can be one of: ON, OFF, REDO, READONLY
[2024-03-25 22:54:36] INFO jit.py:93: Compiling using commands below:
[2024-03-25 22:54:36] INFO jit.py:94: /Users/oflorescu/.pyenv/versions/3.8.18/bin/python -m mlc_llm compile /Users/oflorescu/.cache/mlc_llm/model_weights/mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC --opt 'flashinfer=1;cublas_gemm=1;faster_transformer=1;cudagraph=0;cutlass=1;allreduce_strategy=RING' --overrides 'context_window_size=1024;sliding_window_size=4096;prefill_chunk_size=4096;attention_sink_size=4;tensor_parallel_shards=1' --device metal:0 --output /var/folders/nm/g29p242n0r59m4mm24r9qbtm0000gp/T/tmpt28fxtet/lib.dylib
[2024-03-25 22:54:36] INFO auto_config.py:69: Found model configuration: /Users/oflorescu/.cache/mlc_llm/model_weights/mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC/mlc-chat-config.json
------------------------- Usage -------------------------
usage: __main__.py [-h] [--flashinfer FLASHINFER] [--cublas_gemm CUBLAS_GEMM] [--faster_transformer FASTER_TRANSFORMER]
                   [--cudagraph CUDAGRAPH] [--cutlass CUTLASS] [--allreduce-strategy {ring,one-shot,two-shot}]

optimization flags

optional arguments:
  -h, --help            show this help message and exit
  --flashinfer FLASHINFER
  --cublas_gemm CUBLAS_GEMM
  --faster_transformer FASTER_TRANSFORMER
  --cudagraph CUDAGRAPH
  --cutlass CUTLASS
  --allreduce-strategy {ring,one-shot,two-shot}
------------------------- Error -------------------------
unrecognized arguments: --allreduce_strategy=RING
Traceback (most recent call last):
  File "/Users/oflorescu/.pyenv/versions/3.8.18/lib/python3.8/site-packages/mlc_llm/chat_module.py", line 772, in __init__
    self.model_lib_path = _get_lib_module_path(
  File "/Users/oflorescu/.pyenv/versions/3.8.18/lib/python3.8/site-packages/mlc_llm/chat_module.py", line 591, in _get_lib_module_path
    raise FileNotFoundError(err_msg)
FileNotFoundError: Cannot find the model library that corresponds to `None`.
`None` is either provided in the `chat_config` you passed in, or specified in /Users/oflorescu/.cache/mlc_llm/model_weights/mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC/mlc-chat-config.json.
We searched over the following possible paths:
- None-metal.dylib
- dist/prebuilt/lib/None-metal.dylib
- dist/HF://mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC/None-metal.dylib
- /Users/oflorescu/.cache/mlc_llm/model_weights/mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC/None-metal.dylib
- /Users/oflorescu/.cache/mlc_llm/model_weights/mlc-ai/None-metal.dylib
- None-metal.so
- dist/prebuilt/lib/None-metal.so
- dist/HF://mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC/None-metal.so
- /Users/oflorescu/.cache/mlc_llm/model_weights/mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC/None-metal.so
- /Users/oflorescu/.cache/mlc_llm/model_weights/mlc-ai/None-metal.so
- None-metal.dll
- dist/prebuilt/lib/None-metal.dll
- dist/HF://mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC/None-metal.dll
- /Users/oflorescu/.cache/mlc_llm/model_weights/mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC/None-metal.dll
- /Users/oflorescu/.cache/mlc_llm/model_weights/mlc-ai/None-metal.dll
If you would like to directly specify the model library path, you may consider passing in the `ChatModule.model_lib_path` parameter.
Please checkout https://github.com/mlc-ai/notebooks/blob/main/mlc-llm/tutorial_chat_module_getting_started.ipynb for an example on how to load a model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/oflorescu/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/oflorescu/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/oflorescu/.pyenv/versions/3.8.18/lib/python3.8/site-packages/mlc_llm/__main__.py", line 47, in <module>
    main()
  File "/Users/oflorescu/.pyenv/versions/3.8.18/lib/python3.8/site-packages/mlc_llm/__main__.py", line 36, in main
    cli.main(sys.argv[2:])
  File "/Users/oflorescu/.pyenv/versions/3.8.18/lib/python3.8/site-packages/mlc_llm/cli/chat.py", line 41, in main
    chat(
  File "/Users/oflorescu/.pyenv/versions/3.8.18/lib/python3.8/site-packages/mlc_llm/interface/chat.py", line 133, in chat
    cm = ChatModule(model, device, chat_config=config, model_lib_path=model_lib_path)
  File "/Users/oflorescu/.pyenv/versions/3.8.18/lib/python3.8/site-packages/mlc_llm/chat_module.py", line 785, in __init__
    jit.jit(
  File "/Users/oflorescu/.pyenv/versions/3.8.18/lib/python3.8/site-packages/mlc_llm/interface/jit.py", line 122, in jit
    _run_jit(
  File "/Users/oflorescu/.pyenv/versions/3.8.18/lib/python3.8/site-packages/mlc_llm/interface/jit.py", line 95, in _run_jit
    subprocess.run(cmd, check=True)
  File "/Users/oflorescu/.pyenv/versions/3.8.18/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/oflorescu/.pyenv/versions/3.8.18/bin/python', '-m', 'mlc_llm', 'compile', '/Users/oflorescu/.cache/mlc_llm/model_weights/mlc-ai/Mistral-7B-Instruct-v0.2-q4f16_1-MLC', '--opt', 'flashinfer=1;cublas_gemm=1;faster_transformer=1;cudagraph=0;cutlass=1;allreduce_strategy=RING', '--overrides', 'context_window_size=1024;sliding_window_size=4096;prefill_chunk_size=4096;attention_sink_size=4;tensor_parallel_shards=1', '--device', 'metal:0', '--output', '/var/folders/nm/g29p242n0r59m4mm24r9qbtm0000gp/T/tmpt28fxtet/lib.dylib']' returned non-zero exit status 2.
```

------------------------------------------------------------------------------------------------------------------------
System Settings

  - Apple M1 Pro:
      Chipset Model: Apple M1 Pro
      Type: GPU
      Bus: Built-In
      Total Number of Cores: 16
      Metal Support: Metal 3
 - node version v20.11.1
 - npm version 10.5.0
 
 
 Any suggestions?

**Comment by CharlieFRuan** [comment]
Hi @flores-o, this issue might be better in https://github.com/mlc-ai/mlc-llm, closing this for now.
