### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'origin')

### ISSUE THREAD

**Issue by alucarded** [mlc-ai/web-llm#544]
It seems this is related: https://github.com/mlc-ai/web-llm/issues/124

```
.../node_modules/@mlc-ai/web-llm/lib/index.js:8761
                : globalThis.location.origin;
                                      ^

TypeError: Cannot read properties of undefined (reading 'origin')
    at MLCEngine.<anonymous> (.../node_modules/@mlc-ai/web-llm/lib/index.js:8761:39)
    at Generator.next (<anonymous>)
    at .../node_modules/@mlc-ai/web-llm/lib/index.js:2001:69
    at new Promise (<anonymous>)
    at __awaiter (.../node_modules/@mlc-ai/web-llm/lib/index.js:1997:10)
    at MLCEngine.reloadInternal (.../node_modules/@mlc-ai/web-llm/lib/index.js:8755:16)
    at MLCEngine.<anonymous> (.../node_modules/@mlc-ai/web-llm/lib/index.js:8739:28)
    at Generator.next (<anonymous>)
    at fulfilled (.../node_modules/@mlc-ai/web-llm/lib/index.js:1998:56)

Node.js v18.17.1
```

**Comment by alucarded** [comment]
My mistake, I run this in Node env for testing... btw, would be nice to also be able to experiment with this in node env directly (some chrome.launch() wrapper ?)
