### ISSUE TITLE
Embedding load failing

### ISSUE THREAD

**Issue by djaffer** [mlc-ai/web-llm#638]
```
Error: Cannot find function embed
    at Module.getFunction (index.js:5083:1)
    at VirtualMachine.getFunction (index.js:5213:1)
    at new LLMChatPipeline (index.js:7895:1)
    at MLCEngine.eval (index.js:9940:1)
    at Generator.next (<anonymous>)
    at fulfilled (index.js:2484:41)

```

**Comment by umutbasal** [comment]
if you're using raw appconfig do not forgot model_type field
```
"model_type": webllm.ModelType.embedding,
```
