### ISSUE TITLE
RuntimeError: Cannot find libraries: wasm_runtime.bc

### ISSUE THREAD

**Issue by jan-www** [mlc-ai/web-llm#80]
failed to find library when building model
```
Traceback (most recent call last):
  File "/Users/wangxj/web-llm/build.py", line 200, in <module>
    build(mod, ARGS)
  File "/Users/wangxj/web-llm/build.py", line 174, in build
    ex.export_library(os.path.join(args.artifact_path, output_filename))
  File "/Users/wangxj/web-llm/venv/lib/python3.9/site-packages/tvm/relax/vm_build.py", line 147, in export_library
    return self.mod.export_library(
  File "/Users/wangxj/web-llm/venv/lib/python3.9/site-packages/tvm/runtime/module.py", line 595, in export_library
    return fcompile(file_name, files, **kwargs)
  File "/Users/wangxj/web-llm/venv/lib/python3.9/site-packages/tvm/contrib/emcc.py", line 59, in create_tvmjs_wasm
    libs += [find_lib_path("wasm_runtime.bc")[0]]
  File "/Users/wangxj/web-llm/venv/lib/python3.9/site-packages/tvm/_ffi/libinfo.py", line 152, in find_lib_path
    raise RuntimeError(message)
RuntimeError: Cannot find libraries: wasm_runtime.bc

```

**Comment by yongwww** [comment]
I met this issue on my Ubuntu 22 instance (I built the mlc-ai/relax from source), reason is the web wasm was not built, the script https://github.com/mlc-ai/relax/blob/mlc/tests/scripts/task_web_wasm.sh helps me fix it
